parnames = {1: 'I', 2: 'gCa', 3: 'gK', 4:'STA'}
unames = {1: 'V', 2: 'N'}
NDIM=   2, IPS =   1, IRS =   0, ILP =   1
ICP =  ['I', 'STA']
NTST=  50, NCOL=   6, IAD =   3, ISP =   2, ISW = 1, IPLT= 0, NBC= 0, NINT= 0
NMX=   20000, NPR=  2000, MXBF=  10, IID =   2, ITMX= 8, ITNW= 7, NWTN= 3, JAC= 0
EPSL= 1e-07, EPSU = 1e-07, EPSS =0.0001
DS  =   1e-4, DSMIN=  1e-7, DSMAX= 1e-2, IADS=1
NPAR = 40, THL =  {'PERIOD': 0.0}, THU =  {}
UZSTOP = {'gK': 100.0}
